### ISSUE TITLE
feat: add and replace the BUILD_HASH in any asset file

### ISSUE THREAD

**Issue by chihab** [xlayers/version-stamp#6]
**Is your feature request related to a problem? Please describe.**
I would love to get the version in any asset file: .json,  .txt

**Describe the solution you'd like**
Replace the _BUILD_HASH_ string not only in js assets  `${options.outputPath}/**/*.js` but any configured asset file. The `**/*.js` would be a builder option.

Thanks for this utility, really useful!

**Comment by chihab** [comment]
I couldn't wait to make a PR.  I hope the feature matches the scope of the project :)

**Comment by manekinekko** [comment]
That's awesome. Thank you @chihab 🎉

**Comment by Jefiozie** [comment]
Thank you for the PR @chihab 🎉
